### ISSUE TITLE
Add option to ignore types with default values

### ISSUE THREAD

**Issue by gsingh93** [NathanVaughn/pyleft#91]
It would be nice if there was an option that would ignore untyped arguments with default values. For example:
```python
def foo(bar=True) -> bool:
    return bar

foo()
foo(True)
foo(False)

foo(1)  # pyright already catches this
```

In this case, pyright already handles this properly, and it's obvious from the default value what the type of `bar` is. While there are scenarios where you still would want to add type hints here, I think having the option to disable this would be nice (although if the default value is `None`, the tool should always suggest adding a type hint, regardless of the value of this flag).

**Comment by NathanVaughn** [comment]
I like this idea a lot and will include it in the next release. This motivated me enough to fix some other issues as well.

**Comment by gsingh93** [comment]
I just tested the latest release, it works. Thanks!
